logging:
  config: classpath:logback.xml
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:''}
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  mvc:
    pathmatch:
      #      수정 필요
      matching-strategy: ant_path_matcher
  jpa:
    database: ${JPA_DATABASE:h2}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
weather:
  api:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst
    servicekey: 0HSdpfI%2FdlEQNWKlV25vEjwMJlRCN45jfY8Z1bjbEa4nM%2ByC%2Fo%2B%2FmXc6SWB39UMxajeZKeJPVf4QOrH3IZIU4Q%3D%3D
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /api/**